const WORD_ICONS: Record<string, string> = {

  environment: "🌍", environmental: "🌍", ecology: "🌿", ecosystem: "🌳",
  sustainable: "♻️", sustainability: "♻️", renewable: "♻️", recycle: "♻️",
  pollution: "☣️", climate: "🌡️", global: "🌐", planet: "🪐",
  green: "💚", nature: "🏔️", forest: "🌲", energy: "⚡",
  collaborate: "🤝", collaboration: "🤝", cooperate: "🤝", cooperation: "🤝",
  team: "👥", partnership: "🤝", community: "🏘️",
  technology: "💻", technological: "💻", digital: "📱", innovation: "💡",
  innovate: "💡", computer: "🖥️", software: "💿", data: "📊", internet: "🌐",
  online: "🌐", network: "🌐", device: "📱", machine: "⚙️", robot: "🤖",
  ai: "🧠", artificial: "🧠",
  education: "📚", educate: "📚", educational: "📚", school: "🏫", university: "🎓",
  college: "🎓", study: "📖", learn: "📖", learning: "📖", student: "🧑‍🎓",
  teacher: "👨‍🏫", professor: "👨‍🏫", course: "📋", curriculum: "📋",
  knowledge: "🧠", skill: "🎯", training: "🏋️",
  health: "💊", healthy: "💊", medical: "🏥", hospital: "🏥", disease: "🦠",
  treatment: "💉", medicine: "💊", doctor: "👨‍⚕️", patient: "🤒", surgery: "🔪",
  fitness: "💪", exercise: "🏃", diet: "🥗", nutrition: "🥗", mental: "🧠",
  economy: "💰", economic: "💰", economics: "💰", finance: "💵", financial: "💵",
  money: "💵", budget: "🧾", cost: "🏷️", price: "🏷️", market: "🏪",
  business: "💼", company: "🏢", industry: "🏭", trade: "🤝", income: "💹",
  tax: "🧾", investment: "📈", profit: "📈", revenue: "📊", salary: "💳",
  transport: "🚗", transportation: "🚗", traffic: "🚦", vehicle: "🚗", car: "🚗",
  bus: "🚌", train: "🚆", plane: "✈️", airport: "🛫", travel: "🧳",
  journey: "🧳", commute: "🚇", road: "🛤️", infrastructure: "🏗️",
  culture: "🎭", cultural: "🎭", tradition: "🎊", traditional: "🎊",
  heritage: "🏛️", custom: "🎌", festival: "🎉", art: "🎨", music: "🎵",
  literature: "📖", history: "📜", historical: "📜",
  government: "🏛️", political: "🗳️", politics: "🗳️", policy: "📋",
  law: "⚖️", legal: "⚖️", constitution: "📜", democracy: "🗳️",
  parliament: "🏛️", minister: "👔", election: "🗳️", citizen: "👤",
  society: "👥", social: "👥",
  science: "🔬", scientific: "🔬", research: "🔬", experiment: "🧪",
  laboratory: "🧪", discovery: "🔭", theory: "📐", analysis: "📊",
  analyze: "📊", assess: "📋", evaluate: "📋", measure: "📏",
  calculate: "🧮", method: "⚗️", process: "⚙️", system: "⚙️",
  communication: "💬", communicate: "💬", discuss: "🗣️", discussion: "🗣️",
  conversation: "💬", dialogue: "🗣️", debate: "🎤", speech: "🎤",
  language: "🗣️", express: "💬", expression: "💬",
  explain: "📝", describe: "📝", definition: "📖", define: "📖",
  benefit: "✨", advantage: "✨", disadvantage: "⚠️", positive: "➕",
  negative: "➖", important: "⭐", significant: "🌟", crucial: "🔑",
  critical: "🔑", essential: "🔑", necessary: "📌",
  problem: "❗", issue: "❗", challenge: "🏋️", solution: "💡",
  solve: "🔧", resolve: "🔧",
  however: "🔗", furthermore: "🔗", moreover: "🔗", nevertheless: "🔗",
  therefore: "🔗", consequently: "🔗", thus: "🔗", meanwhile: "🔗",
  although: "🔗", despite: "🔗", whereas: "🔗", while: "🔗",
  because: "🔗", since: "🔗", so: "🔗",
  believe: "🤔", opinion: "💭", think: "🤔", consider: "🤔",
  regard: "👀", perspective: "👁️", view: "👁️", argue: "⚔️",
  claim: "📢", suggest: "💡", recommend: "👍", propose: "📋",
  conclude: "🏁", conclusion: "🏁", summarize: "📝", summary: "📝",
  example: "📌", instance: "📌", case: "📁", illustrate: "🖼️",
  represent: "🎯", indicate: "📊", demonstrate: "📊",
  increase: "📈", decrease: "📉", rise: "📈", fall: "📉",
  grow: "🌱", growth: "🌱", develop: "🔧", development: "🔧",
  improve: "📈", improvement: "📈", enhance: "✨",
  change: "🔄", transform: "🔄", transformation: "🔄",
  differ: "🔀", difference: "🔀", different: "🔀", similar: "🔁",
  compare: "⚖️", comparison: "⚖️", contrast: "🌓",
  ability: "💪", capable: "💪", capacity: "⚡",
  produce: "🏭", production: "🏭", product: "📦", create: "✨",
  creation: "✨", creative: "🎨",
  require: "📋", requirement: "📋", need: "📌", demand: "📈",
  provide: "🤲", supply: "📦", resource: "🧰",
  support: "🤝", maintain: "🔧", maintenance: "🔧",
  structure: "🏗️", structural: "🏗️",
  context: "📋", factor: "🔢", element: "🧩", component: "🔧",
  aspect: "👁️", feature: "✨", quality: "💎", standard: "🏆",
  level: "📊", status: "📊", category: "📁", type: "📝",
  range: "📏", scope: "🎯", scale: "⚖️", extent: "📏",
  access: "🚪",
  technique: "🔧", tool: "🔧", instrument: "🎯",
  focus: "🎯", target: "🎯", goal: "🎯", aim: "🎯",
  task: "📋", activity: "🏃", project: "📁", plan: "📋",
  organize: "📂", organization: "📂", arrange: "🔀",
  manage: "👔", management: "👔", lead: "👑", leader: "👑",
  authority: "👑", power: "⚡", control: "🎛️", influence: "🌊",
  impact: "💥", outcome: "🏁",
  success: "🏆", successful: "🏆", achieve: "🏅", achievement: "🏅",
  fail: "❌", failure: "❌", mistake: "❌", error: "❌",
  correct: "✅", incorrect: "❎", right: "✅", wrong: "❌",
  true: "✅", false: "❎", yes: "👍", no: "👎",
  accept: "✅", reject: "❌", refuse: "🚫",
  allow: "✅", permit: "✅", forbid: "🚫", prohibit: "🚫",
  possible: "🤞", impossible: "🚫", likely: "🎲", unlikely: "🎲",
  certain: "🎯", uncertain: "❓", maybe: "🤷", perhaps: "🤷",
  always: "🔄", never: "🚫", often: "📊", usually: "📊",
  sometimes: "🕐", rarely: "🕐",
  begin: "🏁", start: "🚀", end: "🏁", finish: "🏁",
  continue: "🔄", pause: "⏸️", stop: "🛑", halt: "🛑",
  open: "🚪", close: "🔒",
  enter: "🚶", exit: "🚪", arrive: "🚶", leave: "🏃",
  move: "🚚", transfer: "🔄", shift: "🔀",
  include: "📥", exclude: "📤", contain: "📦",
  add: "➕", remove: "➖", insert: "📥", delete: "🗑️",
  collect: "📥", gather: "📥", distribute: "📤", spread: "🌊",
  connect: "🔗", link: "🔗", attach: "📎", separate: "✂️",
  combine: "🔄", merge: "🔄", divide: "➗", split: "✂️",
  simple: "🔵", complex: "🔷", complicated: "🔷",
  clear: "✨", obvious: "👁️", apparent: "👁️", evident: "👁️",
  hidden: "🕵️", secret: "🤫", private: "🔒", public: "🌍",
  strong: "💪", weak: "🫳", powerful: "💪",
  fast: "⚡", quick: "⚡", rapid: "⚡",
  slow: "🐢", gradual: "🐢",
  big: "🐘", large: "🐘", huge: "🐘", enormous: "🐘",
  small: "🐭", tiny: "🐭", little: "🐭",
  many: "📚", much: "📚", several: "📚", multiple: "📚",
  few: "🔢", some: "🔢",
  first: "🥇", second: "🥈", third: "🥉", last: "🏁",
  next: "⏭️", previous: "⏮️", final: "🏁", initial: "🚀",
  main: "📌", primary: "📌", secondary: "📌",
  major: "⭐", minor: "🔽",
  top: "⬆️", bottom: "⬇️", above: "⬆️", below: "⬇️",
  high: "📈", low: "📉",
  new: "🆕", old: "📜", modern: "🏗️", ancient: "🏛️",
  current: "📅", recent: "🕐",
  early: "🌅", late: "🌆",
  aware: "👁️", conscious: "🧠",
  sure: "✅", doubt: "❓", question: "❓",
  reason: "🧠", cause: "🎯", purpose: "🎯",
  condition: "📋", situation: "📋", circumstance: "📋",
  opportunity: "🚪", chance: "🎲", risk: "⚠️", danger: "☠️",
  safety: "🛡️", security: "🛡️", protection: "🛡️",
  peace: "🕊️", war: "⚔️", conflict: "⚔️",
  freedom: "🕊️", liberty: "🗽",
  justice: "⚖️", equality: "⚖️", fairness: "⚖️",

};export const ICON_BG_COLORS: Record<string, string> = {

  "🌍": "bg-green-100", "🌿": "bg-green-100", "♻️": "bg-emerald-100",
  "☣️": "bg-yellow-100", "🌡️": "bg-orange-100", "🌐": "bg-sky-100",
  "🤝": "bg-purple-100", "👥": "bg-indigo-100", "🏘️": "bg-amber-100",
  "💻": "bg-blue-100", "📱": "bg-cyan-100", "💡": "bg-yellow-100",
  "📊": "bg-blue-100", "⚙️": "bg-gray-100", "🤖": "bg-violet-100",
  "🧠": "bg-pink-100", "📚": "bg-amber-100", "🎓": "bg-indigo-100",
  "📖": "bg-orange-100", "🎯": "bg-red-100", "💊": "bg-red-100",
  "🏥": "bg-red-100", "🦠": "bg-green-100", "💉": "bg-blue-100",
  "💪": "bg-rose-100", "🏃": "bg-lime-100", "🥗": "bg-green-100",
  "💰": "bg-yellow-100", "💵": "bg-green-100", "💼": "bg-blue-100",
  "🏢": "bg-gray-100", "🏭": "bg-orange-100", "📈": "bg-emerald-100",
  "🚗": "bg-blue-100", "🚆": "bg-indigo-100", "✈️": "bg-sky-100",
  "🧳": "bg-amber-100", "🎭": "bg-pink-100", "🎨": "bg-rose-100",
  "🎵": "bg-violet-100", "📜": "bg-amber-100", "🏛️": "bg-gray-100",
  "🗳️": "bg-blue-100", "⚖️": "bg-purple-100", "🔬": "bg-cyan-100",
  "🧪": "bg-teal-100", "🔭": "bg-indigo-100", "💬": "bg-blue-100",
  "🗣️": "bg-indigo-100", "🎤": "bg-pink-100", "✨": "bg-yellow-100",
  "⭐": "bg-amber-100", "🌟": "bg-yellow-100", "🔑": "bg-orange-100",
  "❗": "bg-red-100", "🔗": "bg-gray-100",
  "🤔": "bg-purple-100", "💭": "bg-indigo-100", "👁️": "bg-blue-100",
  "📢": "bg-red-100", "👍": "bg-green-100", "🏁": "bg-gray-100",
  "🔄": "bg-cyan-100", "🌱": "bg-green-100", "🔧": "bg-orange-100",
  "🏆": "bg-amber-100", "💎": "bg-sky-100", "👑": "bg-yellow-100",
  "🌊": "bg-sky-100", "💥": "bg-red-100", "✅": "bg-green-100",
  "❌": "bg-red-100", "🚫": "bg-red-100", "❓": "bg-purple-100",
  "📝": "bg-gray-100", "📋": "bg-blue-100", "📌": "bg-red-100",
  "🎲": "bg-purple-100", "⚠️": "bg-yellow-100", "🛡️": "bg-blue-100",
  "🕊️": "bg-sky-100", "⚔️": "bg-red-100",

};

export function getWordIcon(word: string): string {
  const lower = word.toLowerCase().trim();
  if (WORD_ICONS[lower]) return WORD_ICONS[lower];
  for (const [key, icon] of Object.entries(WORD_ICONS)) {
    if (lower.includes(key)) return icon;
  }
  return "📝";
}

export function getIconBg(icon: string): string {
  return ICON_BG_COLORS[icon] || "bg-gray-100";
}
